INSERT INTO GENRES VALUES (1, 'Genre 1');
INSERT INTO GENRES VALUES (2, 'Genre 2');
INSERT INTO GENRES VALUES (3, 'Genre 3');

INSERT INTO AUTHORS VALUES (1, 'FirstName 1', 'LastName 1');
INSERT INTO AUTHORS VALUES (2, 'FirstName 2', 'LastName 2');
INSERT INTO AUTHORS VALUES (3, 'FirstName 3', 'LastName 3');

INSERT INTO BOOKS VALUES (1, 'Book 1', 1, 1);
INSERT INTO BOOKS VALUES (2, 'Book 2', 2, 2);
INSERT INTO BOOKS VALUES (3, 'Book 3', 3, 3);

INSERT INTO COMMENTS VALUES (1, 'Test comment1', 1);
INSERT INTO COMMENTS VALUES (2, 'Test comment2', 1);