version: '2'
services:
  web-app:
    build: ./
    image: sshumakov/web-app
    ports:
      - 8080:8080
    container_name: web-app
  postgresql:
    extends:
      file: postgresql.yml
      service: postgresql
